//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Distributor
    {
        public string ID { get; set; }
        public string OrgID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Province { get; set; }
        public string Trade { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public Nullable<decimal> Temporary { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
        public string PayMode { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditMan { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<System.DateTime> ExtraEndTime { get; set; }
        public Nullable<decimal> Xded { get; set; }
        public string Jyst { get; set; }
        public string Sj { get; set; }
        public string Wx { get; set; }
        public Nullable<bool> Qktx { get; set; }
        public string Qktxfs { get; set; }
        public Nullable<bool> Tzshtx { get; set; }
        public string Tzshtxfs { get; set; }
        public Nullable<bool> Ddsh { get; set; }
        public Nullable<bool> Sfyh { get; set; }
        public Nullable<bool> Sfkpyh { get; set; }
        public Nullable<bool> Cblbscfhd { get; set; }
        public Nullable<bool> Cqkztfh { get; set; }
        public Nullable<bool> CustomWarehouse { get; set; }
        public Nullable<decimal> Zqndxse { get; set; }
    }
}
